### ISSUE TITLE
Activate script triggers "module: 'go' not found" error

### ISSUE THREAD

**Issue by Aponcher** [eendroroy/promptlib-zsh#2]

**Comment by eendroroy** [comment]
Please give a more details.
Where and how are you using it?

**Comment by Aponcher** [comment]
just running the activate script hit that error after following the setup procedure properly to download the various dependencies

**Comment by eendroroy** [comment]
Try the following the code (save it as a `zsh` script, and then execute):

```zsh
#!/usr/bin/env zsh

source ${0:A:h}/modules.zsh

source ${0:A:h}/activate

echo
echo "  ==> go"
echo -ne "plib_go_version -> " && plib_go_version
echo
echo -ne "plib_goenv_version -> " && plib_goenv_version
echo
```

the `activate` script wasn't supposed to be executed directly.
